name: "Upload git diff as artifact"
description: "Make a git diff and upload the patch as an artifact for local application"

inputs:
  name:
    description: "Name of patch file / artifact"
    required: true
  path:
    description: "Path to git workspace"
    required: true
    default: .

outputs:
  have_diff:
    description: "indicator whether diff was created (1) or not (0)"
    value: ${{ steps.diff.outputs.diff }}

runs:
  using: "composite"
  steps:
    - name: "Create git patch"
      id: diff
      shell: bash
      run: |
        cd "${{ inputs.path }}"
        if ! git diff --quiet ; then
          echo "diff=1" >> "$GITHUB_OUTPUT"
          echo "::warning title=patches available from ${{ inputs.name }}::Download and unzip artifact, and eventually apply patches via: git apply ${{ inputs.name }}.patch"
          git diff > "/tmp/${{ inputs.name }}.patch"
        else
          echo "diff=0" >> "$GITHUB_OUTPUT"
        fi
    - name: Upload patch
      uses: actions/upload-artifact@v3
      if: steps.diff.outputs.diff
      with:
        name: ${{ inputs.name }}
        path: /tmp/${{ inputs.name }}.patch
